name: appvunven
description: "Ứng dụng Quản lý Tài chính Cá nhân - App Vún Vén"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  equatable: ^2.0.7
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  meta: ^1.11.0
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
